[versions]
agp-latest = "9.0.0"
agp-tools = "32.0.0"
detekt = "1.23.6"
dokka = "2.1.0"
kotlin = "2.2.21"
maven-publish = "0.34.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
agp-api7 = { module = "com.android.tools.build:gradle-api", version = "7.4.2" }
agp-api8 = { module = "com.android.tools.build:gradle-api", version = "8.13.2" }
agp-api9 = { module = "com.android.tools.build:gradle-api", version = "9.0.0" }
agp-api-latest = { module = "com.android.tools.build:gradle-api", version.ref = "agp-latest" }
agp-layoutlib = { module = "com.android.tools.layoutlib:layoutlib-api", version.ref = "agp-tools" }
agp-tools-common = { module = "com.android.tools:common", version.ref = "agp-tools" }
agp-tools-manifestmerger = { module = "com.android.tools.build:manifest-merger", version.ref = "agp-tools" }
agp-tools-sdk = { module = "com.android.tools:sdk-common", version.ref = "agp-tools" }

asm = { module = "org.ow2.asm:asm-commons", version = "9.4" }
javassist = { module = "org.javassist:javassist", version = "3.30.2-GA" }
decompiler = { module = "com.jetbrains.intellij.java:java-decompiler-engine", version = "233.14475.28" }
kotlin-metadata = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }

jimfs = { module = "com.google.jimfs:jimfs", version = "1.2" }

gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
kotlinxml = { module = "org.redundent:kotlin-xml-builder", version = "1.8.0" }

dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }

detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-rules-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

kotest = { module = "io.kotest:kotest-assertions-core", version = "5.5.4" }
